services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ems
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    build: .
    command: bash -lc "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      DJANGO_DEBUG: "True"
      DJANGO_SECRET_KEY: "change_me"
      DATABASE_URL: "postgres://postgres:postgres@db:5432/ems"
    ports: ["8000:8000"]
    depends_on:
      db:
        condition: service_healthy
